In [1]:
DATA_PATH = '../data/raw/survey_results_public.csv'

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\abdel\appdata\local\programs\python\python311\lib\site-packages (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\abdel\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\abdel\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\abdel\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.24.1)
Requirement already satisfied: six>=1.5 in c:\users\abdel\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
import pandas as pd
import numpy as np
pd.options.display.max_rows = 10000

In [3]:
raw_df = pd.read_csv(DATA_PATH)

In [4]:
raw_df.head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
4,5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8

In [ ]:
raw_df.isnull().sum()

Respondent                          0
MainBranch                        299
Hobbyist                           45
Age                             19015
Age1stCode                       6561
CompFreq                        24392
CompTotal                       29635
ConvertedComp                   29705
Country                           389
CurrencyDesc                    18989
CurrencySymbol                  18989
DatabaseDesireNextYear          20391
DatabaseWorkedWith              14924
DevType                         15091
EdLevel                          7030
Employment                        607
Ethnicity                       18513
Gender                          13904
JobFactors                      15112
JobSat                          19267
JobSeek                         12734
LanguageDesireNextYear          10348
LanguageWorkedWith               7083
MiscTechDesireNextYear          22082
MiscTechWorkedWith              24147
NEWCollabToolsDesireNextYear    17174
NEWCollabToolsWorkedWith        11578
NEWDevOps                       21775
NEWDevOpsImpt                   22729
NEWEdImpt                       15996
NEWJobHunt                      22175
NEWJobHuntResearch              23439
NEWLearn                         8305
NEWOffTopic                     13657
NEWOnboardGood                  21838
NEWOtherComms                    7256
NEWOvertime                     21230
NEWPurchaseResearch             27140
NEWPurpleLink                    9658
NEWSOSites                       6186
NEWStuck                         9478
OpSys                            8233
OrgSize                         20127
PlatformDesireNextYear          13856
PlatformWorkedWith              10618
PurchaseWhat                    25097
Sexuality                       20469
SOAccount                        7656
SOComm                           7985
SOPartFreq                      17669
SOVisitFreq                      7491
SurveyEase                      12659
SurveyLength                    12760
Trans                           15116
UndergradMajor                  13466
WebframeDesireNextYear          24437
WebframeWorkedWith              22182
WelcomeChange                   11778
WorkWeekHrs                     23310
YearsCode                        6777
YearsCodePro                    18112
dtype: int64

In [ ]:
raw_df.shape

(64461, 61)

In [ ]:
#display random answer
#Observations: Multiple answers need to be splitted 
raw_df.sample(1).iloc[0]

Respondent                                                                  55737
MainBranch                      I used to be a developer by profession, but no...
Hobbyist                                                                      Yes
Age                                                                          34.0
Age1stCode                                                                     18
CompFreq                                                                      NaN
CompTotal                                                                     NaN
ConvertedComp                                                                 NaN
Country                                                                Mozambique
CurrencyDesc                                                                  NaN
CurrencySymbol                                                                NaN
DatabaseDesireNextYear                               MariaDB;Microsoft SQL Server
DatabaseWorkedWith              MariaDB;Microsoft SQL Server;MongoDB;MySQL;Ora...
DevType                         Academic researcher;Database administrator;Sys...
EdLevel                                                                       NaN
Employment                                                     Employed full-time
Ethnicity                                             Black or of African descent
Gender                                                                        Man
JobFactors                                                                    NaN
JobSat                                                                        NaN
JobSeek                                                                       NaN
LanguageDesireNextYear                                                     Kotlin
LanguageWorkedWith               Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;SQL
MiscTechDesireNextYear                                                        NaN
MiscTechWorkedWith                                                            NaN
NEWCollabToolsDesireNextYear                        Github;Gitlab;Microsoft Teams
NEWCollabToolsWorkedWith                            Github;Gitlab;Microsoft Teams
NEWDevOps                                                                     NaN
NEWDevOpsImpt                                                                 NaN
NEWEdImpt                                      Not at all important/not necessary
NEWJobHunt                                                                    NaN
NEWJobHuntResearch                                                            NaN
NEWLearn                                                     Once every few years
NEWOffTopic                                                                    No
NEWOnboardGood                                                                NaN
NEWOtherComms                                                                 Yes
NEWOvertime                                                                   NaN
NEWPurchaseResearch               Visit developer communities like Stack Overflow
NEWPurpleLink                                                   Hello, old friend
NEWSOSites                      Stack Overflow (public Q&A for anyone who code...
NEWStuck                        Meditate;Visit Stack Overflow;Watch help / tut...
OpSys                                                                     Windows
OrgSize                                                                       NaN
PlatformDesireNextYear                    Android;Docker;Kubernetes;Linux;Windows
PlatformWorkedWith                  Android;Docker;Heroku;Linux;Windows;WordPress
PurchaseWhat                                                                  NaN
Sexuality                                                 Straight / Heterosexual
SOAccount                                                                     Yes
SOComm                                                              Yes, somewhat
SOPartFreq                                        A few times per month or weekly
SOVisitFreq                                                  A few times per week
SurveyEase                                             Neither easy nor difficult
SurveyLength                                                             Too long
Trans                                                                          No
UndergradMajor                  Computer science, computer engineering, or sof...
WebframeDesireNextYear                                                     jQuery
WebframeWorkedWith                                                            NaN
WelcomeChange                             Just as welcome now as I felt last year
WorkWeekHrs                                                                   NaN
YearsCode                                                                      12
YearsCodePro                                                                    3
Name: 54627, dtype: object

In [ ]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64461 entries, 0 to 64460
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Respondent                    64461 non-null  int64
 1   MainBranch                    64162 non-null  object
 2   Hobbyist                      64416 non-null  object
 3   Age                           45446 non-null  float64
 4   Age1stCode                    57900 non-null  object
 5   CompFreq                      40069 non-null  object
 6   CompTotal                     34826 non-null  float64
 7   ConvertedComp                 34756 non-null  float64
 8   Country                       64072 non-null  object
 9   CurrencyDesc                  45472 non-null  object
 10  CurrencySymbol                45472 non-null  object
 11  DatabaseDesireNextYear        44070 non-null  object
 12  DatabaseWorkedWith            49537 non-null  object
 13  DevType                       49370 non-null  object
 14  EdLevel                       57431 non-null  object
 15  Employment                    63854 non-null  object
 16  Ethnicity                     45948 non-null  object
 17  Gender                        50557 non-null  object
 18  JobFactors                    49349 non-null  object
 19  JobSat                        45194 non-null  object
 20  JobSeek                       51727 non-null  object
 21  LanguageDesireNextYear        54113 non-null  object
 22  LanguageWorkedWith            57378 non-null  object
 23  MiscTechDesireNextYear        42379 non-null  object
 24  MiscTechWorkedWith            40314 non-null  object
 25  NEWCollabToolsDesireNextYear  47287 non-null  object
 26  NEWCollabToolsWorkedWith      52883 non-null  object
 27  NEWDevOps                     42686 non-null  object
 28  NEWDevOpsImpt                 41732 non-null  object
 29  NEWEdImpt                     48465 non-null  object
 30  NEWJobHunt                    42286 non-null  object
 31  NEWJobHuntResearch            41022 non-null  object
 32  NEWLearn                      56156 non-null  object
 33  NEWOffTopic                   50804 non-null  object
 34  NEWOnboardGood                42623 non-null  object
 35  NEWOtherComms                 57205 non-null  object
 36  NEWOvertime                   43231 non-null  object
 37  NEWPurchaseResearch           37321 non-null  object
 38  NEWPurpleLink                 54803 non-null  object
 39  NEWSOSites                    58275 non-null  object
 40  NEWStuck                      54983 non-null  object
 41  OpSys                         56228 non-null  object
 42  OrgSize                       44334 non-null  object
 43  PlatformDesireNextYear        50605 non-null  object
 44  PlatformWorkedWith            53843 non-null  object
 45  PurchaseWhat                  39364 non-null  object
 46  Sexuality                     43992 non-null  object
 47  SOAccount                     56805 non-null  object
 48  SOComm                        56476 non-null  object
 49  SOPartFreq                    46792 non-null  object
 50  SOVisitFreq                   56970 non-null  object
 51  SurveyEase                    51802 non-null  object
 52  SurveyLength                  51701 non-null  object
 53  Trans                         49345 non-null  object
 54  UndergradMajor                50995 non-null  object
 55  WebframeDesireNextYear        40024 non-null  object
 56  WebframeWorkedWith            42279 non-null  object
 57  WelcomeChange                 52683 non-null  object
 58  WorkWeekHrs                   41151 non-null  float64
 59  YearsCode                     57684 non-null  object
 60  YearsCodePro                  46349 non-null  object
dtypes: float64(4), int64(1), object(56)
memory usage: 30.0+ MB

In [ ]:
raw_df.describe()

         Respondent           Age      CompTotal  ConvertedComp   WorkWeekHrs
count  64461.000000  45446.000000   3.482600e+04   3.475600e+04  41151.000000
mean   32554.079738     30.834111  3.190464e+242   1.037561e+05     40.782174
std    18967.442360      9.585392            inf   2.268853e+05     17.816383
min        1.000000      1.000000   0.000000e+00   0.000000e+00      1.000000
25%    16116.000000     24.000000   2.000000e+04   2.464800e+04     40.000000
50%    32231.000000     29.000000   6.300000e+04   5.404900e+04     40.000000
75%    49142.000000     35.000000   1.250000e+05   9.500000e+04     44.000000
max    65639.000000    279.000000  1.111111e+247   2.000000e+06    475.000000

In [ ]:
questionable_cols = ['YearsCodePro', 'YearsCode', 'Age1stCode']

In [ ]:
for col in questionable_cols:
    print(col)
    print(raw_df[col].unique().tolist())
    print('-'*100)
    print()

YearsCodePro
['27', '4', nan, '8', '13', '2', '7', '20', '1', '23', '3', '12', '17', '18', '10', '14', '29', '6', '28', '9', '15', '11', '16', '25', 'Less than 1 year', '5', '21', '19', '35', '24', '32', '22', '30', '38', '26', '40', '33', '31', 'More than 50 years', '34', '36', '39', '37', '41', '45', '47', '42', '46', '50', '43', '44', '48', '49']
----------------------------------------------------------------------------------------------------

YearsCode
['36', '7', '4', '15', '6', '17', '8', '10', '35', '5', '37', '19', '9', '22', '30', '23', '20', '2', 'Less than 1 year', '3', '13', '25', '16', '43', '11', '38', '33', nan, '24', '21', '12', '40', '27', '50', '46', '14', '18', '28', '32', '44', '26', '42', '31', '34', '29', '1', '39', '41', '45', 'More than 50 years', '47', '49', '48']
----------------------------------------------------------------------------------------------------

Age1stCode
['13', '19', '15', '18', '16', '14', '12', '20', '42', '8', '25', '22', '30', '17', '21', '10', '46', '9', '7', '11', '6', nan, '31', '29', '5', 'Younger than 5 years', '28', '38', '23', '27', '41', '24', '53', '26', '35', '32', '40', '33', '36', '54', '48', '56', '45', '44', '34', 'Older than 85', '39', '51', '68', '50', '37', '47', '43', '52', '85', '64', '55', '58', '49', '76', '72', '73', '83', '63']
----------------------------------------------------------------------------------------------------